CREATE TABLE Bilets
(
    id SMALLINT NOT NULL AUTO_INCREMENT,
    fornavn VARCHAR(255) NOT NULL,
    etternavn VARCHAR(255) NOT NULL,
    telefonNr VARCHAR(255) NOT NULL,
    epost VARCHAR(255) NOT NULL,
    antall INTEGER NOT NULL,
    filmNavn VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);